[package]
name = "astgen"
version = "0.1.0"
authors = ["Matthew Healy <matthew@liamhealy.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
