[package]
name = "rlox"
version = "0.1.0"
authors = ["Matthew Healy <matthew@liamhealy.xyz>"]
edition = "2018"

[dependencies]
astgen = { path = "../astgen" }
peekmore = "0.5.6"
phf = { version = "0.8.0", features = ["macros"] }